GET http://localhost:8080/products

###

POST http://localhost:8080/products/caps
Content-Type: application/json

{
  "name": "Nike",
  "price": 500,
  "color": "green",
  "size": "M"
}

###

POST http://localhost:8080/products/books
Content-Type: application/json

{
  "name": "Anna Karenina",
  "price": 900,
  "author": "Tolstoy",
  "pagesCount": 780
}

###

POST http://localhost:8080/products/iphones
Content-Type: application/json

{ "name": "Iphone",
  "price": 50000,
  "operatingSystem": "ios",
  "memorySize": 64
}

###

POST http://localhost:8080/products/laptops
Content-Type: application/json

{ "name": "Acer",
  "price": 65000,
  "processor": "AMD Radeon",
  "capacitySSD": 256
}

###

GET http://localhost:8080/products/search?text=anna

###

GET http://localhost:8080/products/search?text=tolstoy

###

GET http://localhost:8080/products/search?text=nike

###

GET http://localhost:8080/products/catalog/books

###

GET http://localhost:8080/products/catalog/caps

###

GET http://localhost:8080/products/catalog/iphones

###

GET http://localhost:8080/products/catalog/laptops

###

PUT http://localhost:8080/products/1
Content-Type: application/json

{
  "name": "Red",
  "price": 670
}

###

DELETE http://localhost:8080/products/2

